## This docker-compose file is to be used for development only.

version: "3.4"

services:
  api:
    image: "stevenxie/api:${VERSION}"
    build:
      context: .
      args:
        BUILD_VERSION: "${VERSION}"
      cache_from:
        - stevenxie/api:latest
        - alpine:3.8
    container_name: api
    environment:
      - GOENV=development
    env_file:
      - ./.env
    volumes:
      - type: bind
        source: ./config.yml
        target: /etc/api/config.yml
    networks:
      - public
    ports:
      - "3000:3000" # for development

  varnish:
    image: "cooptilleuls/varnish:6.0.0-alpine"
    volumes:
      - type: bind
        source: ./varnish.vcl
        target: /usr/local/etc/varnish/default.vcl
        read_only: true
    networks:
      - public
    ports:
      - "8080:80"

networks:
  public:
